# Generated by Django 5.1.5 on 2025-02-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='backgrounds/')),
                ('is_the_logo', models.BooleanField(default=False, help_text='Marcar como logo de la pagina')),
            ],
        ),
    ]
