# Generated by Django 5.1.5 on 2025-02-02 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_logos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logos',
            new_name='Logo',
        ),
    ]
