# Generated by Django 5.1.5 on 2025-02-02 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_logo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studioimage',
            name='is_background',
        ),
    ]
