# Generated by Django 5.1.5 on 2025-01-26 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoo',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tattoos', to='tattoos.tattooartist'),
        ),
    ]
