# Generated by Django 5.1.5 on 2025-01-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0002_tattoo_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattooartist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
