# Generated by Django 5.1.5 on 2025-01-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0003_alter_tattooartist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
